# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'feedNews' do
  use_frameworks!

  pod 'lottie-ios'
  pod 'Alamofire', '~> 4.x'
  pod 'Kingfisher', '~> 4.x'

end
